
import type { Vendor, ServiceCategory, SubscriptionPlan, JobRequest } from './types';

export const serviceCategories: ServiceCategory[] = [
  {
    id: 'home-services',
    name: 'Home Services',
    name_gu: 'હોમ સર્વિસ',
    description: 'All your home repair and maintenance needs.',
    imageHint: 'home repair',
    subCategories: [
      { id: 'electrician', name: 'Electrician', name_gu: 'ઇલેક્ટ્રિશિયન' },
      { id: 'plumber', name: 'Plumber', name_gu: 'પ્લમ્બર' },
      { id: 'carpenter', name: 'Carpenter', name_gu: 'સુથાર' },
      { id: 'ac-repair', name: 'AC Repair & Service', name_gu: 'એસી રિપેર અને સર્વિસ' },
      { id: 'refrigerator-repair', name: 'Refrigerator Repair', name_gu: 'રેફ્રિજરેટર રિપેર' },
      { id: 'washing-machine-repair', name: 'Washing Machine Repair', name_gu: 'વોશિંગ મશીન રિપેર' },
      { id: 'ro-service', name: 'RO / Water Purifier Service', name_gu: 'RO / વોટર પ્યુરિફાયર સર્વિસ' },
      { id: 'geyser-repair', name: 'Geyser Repair', name_gu: 'ગીઝર રિપેર' },
      { id: 'chimney-repair', name: 'Chimney Repair', name_gu: 'ચિમની રિપેર' },
    ],
  },
  {
    id: 'cleaning-services',
    name: 'Cleaning Services',
    name_gu: 'સફાઈ સેવાઓ',
    description: 'Professional cleaning for a spotless space.',
    imageHint: 'cleaning supplies',
    subCategories: [
      { id: 'home-deep-cleaning', name: 'Home Deep Cleaning', name_gu: 'ઘરની ઊંડી સફાઈ' },
      { id: 'bathroom-cleaning', name: 'Bathroom Cleaning', name_gu: 'બાથરૂમની સફાઈ' },
      { id: 'kitchen-cleaning', name: 'Kitchen Cleaning', name_gu: 'રસોડાની સફાઈ' },
      { id: 'sofa-cleaning', name: 'Sofa Cleaning', name_gu: 'સોફાની સફાઈ' },
      { id: 'carpet-cleaning', name: 'Carpet Cleaning', name_gu: 'કાર્પેટની સફાઈ' },
      { id: 'office-cleaning', name: 'Office Cleaning', name_gu: 'ઓફિસની સફાઈ' },
      { id: 'water-tank-cleaning', name: 'Water Tank Cleaning', name_gu: 'પાણીની ટાંકીની સફાઈ' },
      { id: 'pest-control', name: 'Pest Control', name_gu: 'પેસ્ટ કંટ્રોલ' },
    ],
  },
  {
    id: 'appliance-services',
    name: 'Appliance Services',
    name_gu: 'એપ્લાયન્સ સર્વિસ',
    description: 'Expert repair for all major appliances.',
    imageHint: 'home appliances',
    subCategories: [
      { id: 'tv-repair', name: 'TV Repair', name_gu: 'ટીવી રિપેર' },
      { id: 'microwave-repair', name: 'Microwave Repair', name_gu: 'માઇક્રોવેવ રિપેર' },
      { id: 'inverter-repair', name: 'Inverter Repair', name_gu: 'ઇન્વર્ટર રિપેર' },
      { id: 'laptop-computer-repair', name: 'Laptop / Computer Repair', name_gu: 'લેપટોપ / કમ્પ્યુટર રિપેર' },
      { id: 'mobile-repair', name: 'Mobile Repair', name_gu: 'મોબાઇલ રિપેર' },
      { id: 'cctv-installation', name: 'CCTV Installation', name_gu: 'સીસીટીવી ઇન્સ્ટોલેશન' },
    ],
  },
  {
    id: 'construction-repair',
    name: 'Construction & Repair',
    name_gu: 'બાંધકામ અને સમારકામ',
    description: 'Building, renovating, and repairing structures.',
    imageHint: 'construction tools',
    subCategories: [
      { id: 'painting', name: 'Painting (Interior / Exterior)', name_gu: 'પેઇન્ટિંગ (આંતરિક / બાહ્ય)' },
      { id: 'false-ceiling', name: 'False Ceiling', name_gu: 'ફોલ્સ સિલિંગ' },
      { id: 'waterproofing', name: 'Waterproofing', name_gu: 'વોટરપ્રૂફિંગ' },
      { id: 'tile-flooring-work', name: 'Tile / Flooring Work', name_gu: 'ટાઇલ / ફ્લોરિંગ કામ' },
      { id: 'welding-work', name: 'Welding Work', name_gu: 'વેલ્ડિંગ કામ' },
      { id: 'glass-aluminum-work', name: 'Glass & Aluminum Work', name_gu: 'ગ્લાસ અને એલ્યુમિનિયમ કામ' },
    ],
  },
  {
    id: 'outdoor-utility',
    name: 'Outdoor & Utility',
    name_gu: 'આઉટડોર અને યુટિલિટી',
    description: 'Services for your garden and utilities.',
    imageHint: 'gardening tools',
    subCategories: [
      { id: 'gardening', name: 'Gardening', name_gu: 'બાગકામ' },
      { id: 'tree-cutting', name: 'Tree Cutting', name_gu: 'વૃક્ષ કાપણી' },
      { id: 'borewell-service', name: 'Borewell Service', name_gu: 'બોરવેલ સર્વિસ' },
      { id: 'solar-panel-installation', name: 'Solar Panel Installation', name_gu: 'સોલાર પેનલ ઇન્સ્ટોલેશન' },
      { id: 'generator-repair', name: 'Generator Repair', name_gu: 'જનરેટર રિપેર' },
    ],
  },
  {
    id: 'vehicle-services',
    name: 'Vehicle Services',
    name_gu: 'વાહન સેવાઓ',
    description: 'Keep your car and bike in top condition.',
    imageHint: 'car wheel',
    subCategories: [
      { id: 'car-wash', name: 'Car Wash', name_gu: 'કાર વોશ' },
      { id: 'bike-wash', name: 'Bike Wash', name_gu: 'બાઇક વોશ' },
      { id: 'car-repair', name: 'Car Repair', name_gu: 'કાર રિપેર' },
      { id: 'bike-repair', name: 'Bike Repair', name_gu: 'બાઇક રિપેર' },
      { id: 'battery-replacement', name: 'Battery Replacement', name_gu: 'બેટરી રિપ્લેસમેન્ટ' },
      { id: 'puncture-service', name: 'Puncture Service', name_gu: 'પંચર સર્વિસ' },
      { id: 'roadside-assistance', name: 'Roadside Assistance', name_gu: 'રોડસાઇડ સહાય' },
    ],
  },
  {
    id: 'personal-services',
    name: 'Personal Services',
    name_gu: 'વ્યક્તિગત સેવાઓ',
    description: 'Beauty and wellness services at your home.',
    imageHint: 'salon scissors',
    subCategories: [
      { id: 'salon-at-home-men', name: 'Salon at Home (Men)', name_gu: 'સલૂન એટ હોમ (પુરુષો)' },
      { id: 'salon-at-home-women', name: 'Salon at Home (Women)', name_gu: 'સલૂન એટ હોમ (મહિલાઓ)' },
      { id: 'haircut', name: 'Haircut', name_gu: 'હેરકટ' },
      { id: 'makeup-artist', name: 'Makeup Artist', name_gu: 'મેકઅપ આર્ટિસ્ટ' },
      { id: 'massage-therapy', name: 'Massage Therapy', name_gu: 'મસાજ થેરાપી' },
      { id: 'mehndi-artist', name: 'Mehndi Artist', name_gu: 'મહેંદી આર્ટિસ્ટ' },
    ],
  },
  {
    id: 'event-services',
    name: 'Event & Occasion',
    name_gu: 'ઇવેન્ટ અને પ્રસંગ',
    description: 'Everything you need for your special event.',
    imageHint: 'event decoration',
    subCategories: [
      { id: 'event-decoration', name: 'Event Decoration', name_gu: 'ઇવેન્ટ ડેકોરેશન' },
      { id: 'tent-house', name: 'Tent House', name_gu: 'ટેન્ટ હાઉસ' },
      { id: 'dj-sound-system', name: 'DJ & Sound System', name_gu: 'ડીજે અને સાઉન્ડ સિસ્ટમ' },
      { id: 'photographer', name: 'Photographer', name_gu: 'ફોટોગ્રાફર' },
      { id: 'videographer', name: 'Videographer', name_gu: 'વિડિયોગ્રાફર' },
      { id: 'catering-service', name: 'Catering Service', name_gu: 'કેટરિંગ સર્વિસ' },
    ],
  },
    {
    id: 'digital-professional',
    name: 'Digital & Professional',
    name_gu: 'ડિજિટલ અને પ્રોફેશનલ',
    description: 'Tech and professional services.',
    imageHint: 'laptop computer',
    subCategories: [
        { id: 'computer-service', name: 'Computer Service', name_gu: 'કમ્પ્યુટર સર્વિસ' },
        { id: 'printer-repair', name: 'Printer Repair', name_gu: 'પ્રિન્ટર રિપેર' },
        { id: 'internet-wifi-setup', name: 'Internet / WiFi Setup', name_gu: 'ઇન્ટરનેટ / વાઇફાઇ સેટઅપ' },
        { id: 'cctv-amc', name: 'CCTV AMC', name_gu: 'સીસીટીવી એએમસી' },
        { id: 'website-development', name: 'Website Development', name_gu: 'વેબસાઇટ ડેવલપમેન્ટ' },
    ]
  },
  {
    id: 'care-services',
    name: 'Care Services',
    name_gu: 'સંભાળ સેવાઓ',
    description: 'Personal care for your loved ones.',
    imageHint: 'health care',
    subCategories: [
        { id: 'babysitting', name: 'Babysitting', name_gu: 'બેબીસીટિંગ' },
        { id: 'elderly-care', name: 'Elderly Care', name_gu: 'વૃદ્ધોની સંભાળ' },
        { id: 'patient-care-attendant', name: 'Patient Care Attendant', name_gu: 'દર્દી સંભાળ એટેન્ડન્ટ' },
        { id: 'nurse-at-home', name: 'Nurse at Home', name_gu: 'નર્સ એટ હોમ' },
    ]
  },
  {
    id: 'business-commercial',
    name: 'Business / Commercial',
    name_gu: 'બિઝનેસ / કોમર્શિયલ',
    description: 'Services tailored for businesses.',
    imageHint: 'office building',
    subCategories: [
        { id: 'office-cleaning', name: 'Office Cleaning', name_gu: 'ઓફિસની સફાઈ' },
        { id: 'office-ac-service', name: 'Office AC Service', name_gu: 'ઓફિસ એસી સર્વિસ' },
        { id: 'security-guard-service', name: 'Security Guard Service', name_gu: 'સિક્યુરિટી ગાર્ડ સર્વિસ' },
        { id: 'housekeeping-staff', name: 'Housekeeping Staff', name_gu: 'હાઉસકીપિંગ સ્ટાફ' },
    ]
  }
];


export const vendors: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Reliable Plumbers',
    phone: '+11234567890',
    location: '23.7337, 69.8597',
    serviceCategory: 'Plumber',
    rating: 4.8,
    currentWorkload: 2,
    subscriptionStatus: 'active',
    isOnline: true,
    workingRadius: 15,
    approved: true,
  },
  {
    id: 'vendor-2',
    name: 'Sparky Electrics',
    phone: '+12345678901',
    location: '23.2156, 72.6369',
    serviceCategory: 'Electrician',
    rating: 4.5,
    currentWorkload: 5,
    subscriptionStatus: 'active',
    isOnline: false,
    workingRadius: 20,
    approved: true,
  },
  {
    id: 'vendor-3',
    name: 'Clean Sweep Co.',
    phone: '+13456789012',
    location: '23.0225, 72.5714',
    serviceCategory: 'Home Deep Cleaning',
    rating: 4.9,
    currentWorkload: 1,
    subscriptionStatus: 'expired',
    isOnline: true,
    workingRadius: 25,
    approved: true,
  },
  {
    id: 'vendor-4',
    name: 'Paint Perfect',
    phone: '+14567890123',
    location: '22.3072, 73.1812',
    serviceCategory: 'Painting (Interior / Exterior)',
    rating: 4.7,
    currentWorkload: 3,
    subscriptionStatus: 'active',
    isOnline: true,
    workingRadius: 10,
    approved: false,
  },
  {
    id: 'vendor-5',
    name: 'Handy Woodworks',
    phone: '+15678901234',
    location: '21.1702, 72.8311',
    serviceCategory: 'Carpenter',
    rating: 4.6,
    currentWorkload: 0,
    subscriptionStatus: 'inactive',
    isOnline: false,
    workingRadius: 30,
    approved: true,
  },
];

export const subscriptionPlans: SubscriptionPlan[] = [
  { id: 'plan-daily', name: 'Daily', price: 10, durationDays: 1 },
  { id: 'plan-weekly', name: 'Weekly', price: 50, durationDays: 7 },
  { id: 'plan-monthly', name: 'Monthly', price: 180, durationDays: 30 },
];

export const jobRequests: JobRequest[] = [
    {
        id: 'job-1',
        name: 'Thakkar Yash Manoj Kumar',
        phone: '9106433706',
        pincode: '370001',
        locality: 'Bhuj',
        address: 'opp. jalaram temple new raghuvanshi nager behind the bhanushali nager',
        city: 'BHUJ',
        state: 'Gujarat',
        customerLocation: { latitude: 23.2549, longitude: 69.6631 },
        serviceCategory: 'Plumbing',
        description: 'Leaky faucet in the kitchen sink.',
        status: 'assigned',
        vendorId: 'vendor-1',
        createdAt: new Date(2023, 10, 15, 10, 30),
    },
    {
        id: 'job-2',
        name: 'Jane Smith',
        phone: '9876543210',
        pincode: '380009',
        locality: 'Navrangpura',
        address: '123 Commerce House',
        city: 'Ahmedabad',
        state: 'Gujarat',
        customerLocation: { latitude: 23.037, longitude: 72.55 },
        serviceCategory: 'Electrical',
        description: 'Install a new ceiling fan.',
        status: 'pending',
        createdAt: new Date(2023, 10, 16, 14, 0),
    },
     {
        id: 'job-3',
        name: 'Peter Jones',
        phone: '9988776655',
        pincode: '390007',
        locality: 'Alkapuri',
        address: 'GF-5, Paradise Complex',
        city: 'Vadodara',
        state: 'Gujarat',
        customerLocation: { latitude: 22.310, longitude: 73.172 },
        serviceCategory: 'Plumbing',
        description: 'Clogged toilet, needs urgent attention.',
        status: 'completed',
        vendorId: 'vendor-1',
        createdAt: new Date(2023, 10, 14, 9, 0),
    },
];
