// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {"apiKey":"AIzaSyDj1kyUARo--lomvruPJbQqbVlrVTN9uDk","appId":"1:295789510181:web:d8d8a1418e60349d8c89cc","authDomain":"jalram-home-services.firebaseapp.com","measurementId":"","messagingSenderId":"295789510181","projectId":"jalram-home-services"};
